name:                ODPServer
version:             0.1.0.0

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- either
- http-conduit
- http-types
- stm
- text
- unordered-containers
- url
- wai
- wai-websockets
- warp
- websockets
- wuss

executables:
  ODPServer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  ODPServer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
