name: Check

on: [ push, pull_request ]

jobs:
  build:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Source code formatting check
        uses: mrkkrp/ormolu-action@v1

      - name: Check
        run: |
          stack build --fast
          stack test
